# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "DB Checkout"
client_id = "92a1b41af1e86b582b470b0b320f825c"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,read_orders,read_shipping,unauthenticated_read_customers,unauthenticated_read_customer_tags,unauthenticated_read_product_listings,unauthenticated_read_product_tags"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "db-checkout-preview.myshopify.com"
