# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "DB Checkout"
client_id = "d6b00101ddbaeaf5017c273843043bc8"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,read_customers,read_product_listings,read_products,read_orders,read_shipping,unauthenticated_read_customers,unauthenticated_read_customer_tags,unauthenticated_read_product_listings,unauthenticated_read_product_tags,customer_read_customers"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "db-checkout-dev.myshopify.com"
