# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "db-checkout-extensibility"
client_id = "f3bc460c3142d44b5882bb4cef78a8d1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
dev_store_url = "db-checkout-ext.myshopify.com"
